### ISSUE TITLE
 Minor Update: Update "let's go" button on homepage

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#105]
Update the "let's go" button to look like the Figma and make clicking it redirect to the demo page.
![image](https://user-images.githubusercontent.com/78634083/201459124-9b11f53a-38f3-4e3e-b96d-a4cd5a06f94b.png)

**Comment by ajtadeo** [comment]
I forgot to reference the issue in my commit messages, but the following commits reference this issue:
a4d618a725ccce3103c3ebff07fe37294b3add17
206429c93321fe2a5a9b328856dc2604da8e5cb6

**Comment by ajtadeo** [comment]
Start button onclick method links to "/lesson-1" because no "why-pointers" page exists yet. This should be fixed in a future issue.

**Comment by ajtadeo** [comment]
I was getting an error with a fresh `yarn.lock` file, but solved using `git checkout origin/main -- yarn.lock` as explained here: https://github.com/yarnpkg/yarn/issues/6152#issuecomment-469490433

**Comment by Dankco** [comment]
Don't worry about referencing the issue in commit messages, just reference it in the PR itself (and maybe the branch name). The PR linked will close the issue automatically, so that is probably most important.

**Comment by Alkhatri77** [comment]
> Update the "let's go" button to look like the Figma and make clicking it redirect to the demo page.
> ![image](https://user-images.githubusercontent.com/78634083/201459124-9b11f53a-38f3-4e3e-b96d-a4cd5a06f94b.png)
>
