### ISSUE TITLE
Feature: Drag and drop component

### ISSUE THREAD

**Issue by ColbertX** [uclaacm/parcel-pointers#16]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/79346706/168210145-32457fed-e3f4-40a6-9efe-ade30b664b5f.png">

Implement drag and drop section, using whatever libraries you need. Start by creating an "exercise-1" page, so you can work on this page. At the moment we haven't fleshed out the exercise page yet, so you don't need to worry about styling since we'll have to go back and format the whole page later anyway. We'll save styling for another ticket, so for this one you should focus on just getting as much functionality done as you can

Desired behaviors for the drag and drop (do as much of this as you want, if you decide that you've spent too long working on this ticket and want to move on to something else that's fine too, we can save the rest for another ticket) -
* Users can drag the items to the boxes, and as long as they drop it somewhere near the box, the item should click into place
* If the user drops the item in a place that is not near a box, then the item should not be placed down and it should return to the original position that the user picked it up from, so the user knows they need to try again
* If the user drops an item onto a box that already has an item in it, the box should be replaced with the new item
* If a box already contains an answer, the user can remove the answer by dragging the item out of the box and dropping it somewhere not near the box. It should be returned to the selection area, next to the other items

Honestly I'm not sure how feasible a lot of this is since I don't know too much about the library, so message me in discord with any questions/updates you have
Good luck!

**Comment by Dankco** [comment]
Might revisit this later, but we should probably explore other simpler options for now.
