### ISSUE TITLE
Minor Update: Copy-to-clipboard button for code snippets

### ISSUE THREAD

**Issue by ajtadeo** [uclaacm/parcel-pointers#164]
Something useful for users could be a copy-to-clipboard button in the top-right corner of each code snippet. This youtube video gives a great guide on how to accomplish this with react-syntax-highlighter -- which is also what we're using for the Terminal component. 

https://www.youtube.com/watch?v=iAAOvv_4ONI&ab_channel=%C3%87elikK%C3%B6seo%C4%9Flu

Reference Image:
![image](https://user-images.githubusercontent.com/76643809/221340203-3897c292-d03e-47ef-81e1-64d58fd627a6.png)

Current Terminal Component:
![image](https://user-images.githubusercontent.com/76643809/221340255-9b2fed0f-7c01-47d7-86b9-8463bc4f3cba.png)

**Comment by ajtadeo** [comment]
@Dankco @lawtlee noticed a bug when testing out this feature. the text box for "copied to clipboard" isn't centered when changing the viewport width and the code snippet component seems to adjust its position on the page when its clicked. great progress :)

https://github.com/uclaacm/parcel-pointers/assets/76643809/33d8ebca-561c-41fa-b2b8-ecef20381c99

**Comment by lawtlee** [comment]
@ajtadeo @Dankco I fixed the error with the centering and the component interrupting the dom with the latest push. I couldn't get it to look right on mobile though since everything seems to be messed up for the mobile viewport at the moment.

https://github.com/uclaacm/parcel-pointers/assets/104863284/de2e433f-fa79-4b2c-818b-ae3d47cc7498

**Comment by Dankco** [comment]
Yeah, I will ticket some of the main mobile issues, but there are a lot of mobile issues with the app right now because we did not design with mobile screens in mind.
Obviously, we do need to make this better though going forward.
