### ISSUE TITLE
Feature: Implement front page

### ISSUE THREAD

**Issue by ColbertX** [uclaacm/parcel-pointers#17]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/79346706/168344648-f4120590-7816-485d-8a3c-f7ede8c77d76.png">

Implement the front page in the Home.tsx file, according to the figma design
You don't need to worry about the little sidebar at the top, since someone else should be taking care of that for you
You can leave the "let's go" button as just a normal button where nothing happens if you click on it, but if you feel up to a challenge you can try redirecting the user to the lesson-1 page if they click on it!
Apart from that, this page shouldn't be dependent on any of the other pages, so don't worry about how any of the other code is going to affect your Home.tsx file

If you happen to think of a snappy description to put on the home page, feel free to add it!
And of course, if you have any questions feel free to reach out to any of us! Good luck!

**Comment by sweeneyngo** [comment]
Fixed issue with Pipi existing below in the wrong flex-direction!
