### ISSUE TITLE
Minor Update: Popup closes if user clicks off it

### ISSUE THREAD

**Issue by ColbertX** [uclaacm/parcel-pointers#26]
Very minor update, I think it would be nice if in addition to the user clicking on the close button to get rid of the popup, they could also just click somewhere on the screen that's off the popup to close it.

**Comment by Dankco** [comment]
@brad-lowe are you working on this ticket or the slideshow component one #30 ?

**Comment by ajtadeo** [comment]
FYI I implemented a click-out feature for the sidebar menu. If you want to reference it, it's in Sidebar.tsx line 113.
