### ISSUE TITLE
Feature: Add Code clicking component

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#297]
Create a component where clicking on a given line of code should load the corresponding image.
Put the component into the Lesson 5 page here:
<img width="693" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/78634083/22ff4d27-26fb-40c7-b038-237d8f224338">
Will be here on the site.
<img width="1508" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/78634083/8b5d9a8e-8f2b-4ce7-96d9-67a927e3eab2">

**Comment by lawtlee** [comment]
is there a figma with the diarams?
