### ISSUE TITLE
Minor Update: Reduce size of slideshow arrows for smaller screens

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#371]
![image](https://github.com/uclaacm/parcel-pointers/assets/78634083/44b5ac28-5695-4d50-8717-d40f95002c5a)
Let's reduce the size of these slideshow arrows and make it so that they don't cover the image (or at least not as much) for smaller screens.

**Comment by Dankco** [comment]
This is already done actually

**Comment by Dankco** [comment]
Assigning @lilyorlilypad for point purposes lol

**Comment by lilyorlilypad** [comment]
Should I do anything lol? I saw that it's already done
