### ISSUE TITLE
Minor Update: Add prop for no animation on arrow diagram

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#376]
Add a prop that makes it so that there is no animation on the arrow diagram and instead looks like this from the [Figma](https://www.figma.com/file/s58gyNCNvAQUM4pYAkHXF5/Pointers-Learning-Lab?type=design&node-id=628-2524&mode=design&t=LCTQjlE474DNVbxr-0):
![image](https://github.com/uclaacm/parcel-pointers/assets/78634083/2cc6b6bc-7713-4aa9-91de-6efa93c5a38f)

Let's also not have the arrow on lesson 3 or the first arrow on lesson 4 be animated.

**Comment by lilyorlilypad** [comment]
I added the prop and made the arrow on lesson 3 & the first arrow on lesson 4 not animated. Do you mean want all the arrow diagrams without animation look like the picture you attached above?

They look like this right now:
<img width="819" alt="截屏2024-01-22 下午11 12 49" src="https://github.com/uclaacm/parcel-pointers/assets/105081034/28f1250f-0bd6-479c-90dc-7b58719b09c9">

**Comment by Dankco** [comment]
I think the idea from the Figma just having the pointer filled in was to indicate that the pointer was being "selected". Then for dereferencing, it would move the "selection" from the pointer to the variable.
However, upon looking at this now, I don't know if that idea is super clear. What do you think?

**Comment by lilyorlilypad** [comment]
It wasn't super clear to me, but now you mention it, it kind of makes sense. I think it is not that straightforward. People need to think a while to get that implication.

**Comment by Dankco** [comment]
Ok, then yeah I think we should add some text just explaining the picture and the idea of "selection" unless you can think of a way to change it to make it look more clear. Feel free to just rephrase my comment from above.
