### ISSUE TITLE
Feature: Create new Code Filling Component

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#390]
Make a new code fill component to be put into the Exercise 2 page here:
![image](https://github.com/uclaacm/parcel-pointers/assets/78634083/5ac9781c-1cc5-4e2e-9375-802095fb4e1b)

**Comment by lawtlee** [comment]
Am I allowed to add packages?

**Comment by lawtlee** [comment]
Also am I adding the run option?

**Comment by Dankco** [comment]
Yes, adding packages is fine. Preferably yes, but its just a dropdown state checker, not actually running the code.

**Comment by lawtlee** [comment]
So something like this?
<img width="601" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/104863284/5cfe9339-3d9e-4647-8fbf-f310100c9a9a">

**Comment by Dankco** [comment]
yeah something like that looks fine.

**Comment by Dankco** [comment]
Still left to do:
1. "Run" button to check for the correct answer in dropdown
2. Adding highlighting in a larger modular component with some initial code text as children

**Comment by lawtlee** [comment]
I don't really get the 2nd part to the still left to do

**Comment by Dankco** [comment]
Oh yeah, upon reading again I get why.
Basically, I was talking about the gray highlighting, so we can have 3 bigger components in a page like this:
![image](https://github.com/uclaacm/parcel-pointers/assets/78634083/362800e2-3d42-4ae4-bcd2-ca091f1270f1)

It would be analogous to this [question component](https://github.com/uclaacm/parcel-pointers/blob/main/src/components/Question.tsx) from excercise 1.

**Comment by lawtlee** [comment]
This is what I have rn:
![image](https://github.com/uclaacm/parcel-pointers/assets/104863284/9e34e887-9df7-4c26-968b-4ae80978a898)
