### ISSUE TITLE
Minor Update: Expand Runcode Component Functionality

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#428]
Thanks to Lily for writing these up.
Some issues with the Runcode component:

1. It doesn't display the placerholder "select"
~~2. It currently only accepts one answer as correct~~
~~3. There is no way display different messages for different incorrect choices.~~
~~4. Needs to be able to support the functionality here:~~
<img width="677" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/78634083/ceddb59f-5fc6-457f-a060-612af02dad91">

See comments on Figma for details, but basically we can make the dropdown either multi-select supported or just have the first correct text show up when they get one answer, then only show the second correct text once they get the other answer.

~~5. part of this other [ticket](https://github.com/uclaacm/parcel-pointers/issues/429), but it does not fit well with mobile screens.~~

**Comment by lawtlee** [comment]
@Dankco Is this still an issue that needs to be fixed?

**Comment by Dankco** [comment]
Yes, 1-4 still need to be fixed. My PR here made other changes.
https://github.com/uclaacm/parcel-pointers/pull/460

**Comment by lawtlee** [comment]
For the UX for this are we going with allowing the user to select multiple different answer choices or checkboxes.

**Comment by Dankco** [comment]
Honestly I think either is fine. Whichever you think is easier to implement I guess? One thing to consider though is that checkboxes take up more room than highlighting the selections.

**Comment by Dankco** [comment]
Also, just double-checked that there are no multi-line selections that have multiple correct answers, only single-line selections with multiple correct answers and multi-line selections with one correct answer.

**Comment by Dankco** [comment]
@lawtlee whats the status on this?
I think I am going to pick up 3 first so that we won't have to make as much of a change to the exercise pages once the rest is implemented.

**Comment by Dankco** [comment]
I ended up basically doing this entire ticket lol. I am just going to finish it off.
