### ISSUE TITLE
Minor Update: Hint Box Correct/Incorrect State Updates

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#432]
I realized that we never made the Hint Box update when an address is clicked in the Demo Page, or in the Exercise 3 Page.
Let's make an incorrect state (that cannot be clicked on to close) like the one here when the user clicks the wrong address:
<img width="639" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/78634083/6b796884-33c4-4095-ac1a-812ea639c3e5">
And let's have a correct state (that cannot be clicked on to close) like the one here when the user clicks the right address:
<img width="774" alt="image" src="https://github.com/uclaacm/parcel-pointers/assets/78634083/ea8a3737-3e11-40a1-a5dd-962c9f1a13be">

**Comment by tiffanyorian** [comment]
It gives me a 404 error when i try to find exercises 3 page
