### ISSUE TITLE
Minor Update: Investigate multi-line dropdown

### ISSUE THREAD

**Issue by Dankco** [uclaacm/parcel-pointers#454]
Exercise 6 requires some multi-line options. Let's investigate if this is possible using the existing component (Chengheng says its possible) and make an example of this so that we don't have any surprises when we start on Exercise 6.
Example taken from content plan:
Which code segment correctly starts the linked list?
{
	Node* head; // head Node, assume Node class is defined
	Node* tail; // tail Node
	(Dropdown- each option has multiple lines)
head = new Node();
		tail = new Node();
		head->next = *head;
		tail->next = *head;
		Not quite, the tail-> next = *head would circle back to the head node and we are not trying to create a circular linked list
head = new Node();
		head->next = new Node();
		head->next = head;
		tail = head->next;
Not quite, head->next = head would make the head node’s next pointer point to itself
*head = new Node();
		*(head->next) = new Node();
		*(head->next->prev) = *head;
		tail = *head->next;
		Not quite, remember that the new keyword gives us a pointer, not an object
head = new Node();
		head-> next = new Node();
		tail = head->next;
		head->next->prev = head;
		Correct! Let’s go through this line by line. The first line creates a new node and assigns head to point to it. The second line creates a second node and assigns the head node’s next pointer to point to it. The third line assigns tail to point at the second node, since it copies the head node’s next pointer. The fourth line actually simplifies to tail->prev = *head, since from the third line we know tail = head->next, it assigns the previous pointer of the tail node to point back to the head node.
}

We should have:
- [ ] a new Exercise 6 page
- [ ] with just a multi-line dropdown
- [ ] that is filled with the text from the content plan here.

**Comment by ChenghengLi** [comment]
You can easily admit "/n" characters formatting the choices to select in selectCode.tsx. Just add  
```
<pre><code>{choice}</code></pre> 
```
at 
```
{choice} 
```
and the choice will admit "/n" characters. 

Already made this modification at the exercise 6 branch.

**Comment by YPandas** [comment]
Got it! But there seems to be some formatting issues with the correct text,
I’ll try to fix it tonight
ChenghengLi ***@***.***>于2024年2月20日 周二16:53写道：
