### ISSUE TITLE
Minor Update: Make people select an answer before checking it

### ISSUE THREAD

**Issue by lilyorlilypad** [uclaacm/parcel-pointers#458]
In exercise 1, people can click on "check" before they select any answer and they will get the hint "Not quite...". 

![Image](https://github.com/uclaacm/parcel-pointers/assets/105081034/939d14b3-3cdb-46e7-bf76-5f1216a30ef8)

We probably want to give them a warning if they click on check without selecting an answer instead of giving the hint away.

**Comment by Dankco** [comment]
@tiffanyorian what is the status here? If you have not started, I can pick this up.
